### ISSUE TITLE
Need more space, power and work

### ISSUE THREAD

**Issue by TheRealNachtfalter** [Codingwal/Accropoly#10]
Add bigger template map and explain how to place the solar-panels and office buildings.

**Comment by TheRealNachtfalter** [comment]
Or simply publish the 0.0.9 + upload a bigger template map 😉

**Comment by Codingwal** [comment]
I think the game could use some design instead. I wonder whose job that is...

**Comment by TheRealNachtfalter** [comment]
Now, almost one year later, office buildings and solar panels + wind turbines are in the game.
